name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  TEST_FOLDER: ${{github.workspace}}/test

jobs:
  build:
    runs-on: ubuntu-latest # TODO: Setup build matrix

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get -y install libcurl4-openssl-dev libgtest-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
#      working-directory: ${{github.workspace}}/build
      run: cd ${{github.workspace}}/build && GTEST_OUTPUT="xml:output/" ctest -C ${{env.BUILD_TYPE}} --extra-verbose

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always() # Only runs on ubuntu:latest
      with:
        files: ${{github.workspace}}/build/test/output/**/*.xml
